# Generated by Django 5.2.5 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=128, verbose_name="Space #")),
                (
                    "info",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Description"
                    ),
                ),
            ],
        ),
    ]
