# Generated by Django 5.2.5 on 2025-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="number",
            field=models.IntegerField(verbose_name="Space #"),
        ),
    ]
