# Generated by Django 5.2.5 on 2025-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0002_alter_space_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="number",
        ),
    ]
