# Generated by Django 5.2.5 on 2025-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0003_remove_space_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="number",
            field=models.IntegerField(default=0, verbose_name="Space #"),
        ),
    ]
