# Generated by Django 5.2.5 on 2025-08-19 08:38

import django.db.models.functions.window
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0005_alter_space_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="number",
            field=models.IntegerField(
                default=django.db.models.functions.window.LastValue,
                unique=True,
                verbose_name="Space #",
            ),
        ),
    ]
