# Generated by Django 5.2.5 on 2025-08-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0006_alter_space_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="number",
            field=models.IntegerField(unique=True, verbose_name="Space #"),
        ),
    ]
