# Generated by Django 5.2.5 on 2025-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="created",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="memberskill",
            name="created",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="created",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="sort",
            field=models.IntegerField(default=1, verbose_name="Order"),
        ),
    ]
