# Generated by Django 5.2.5 on 2025-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_image_created_image_modified_member_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(
                blank=True, upload_to="members/", verbose_name="Url"
            ),
        ),
    ]
