# Generated by Django 5.2.5 on 2025-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="sort",
            field=models.IntegerField(default=1, unique=True, verbose_name="Order"),
        ),
    ]
