# Generated by Django 5.2.5 on 2025-08-15 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_image_sort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="memberskill",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
