# Generated by Django 5.2.5 on 2025-08-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_image_member_alter_memberskill_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="employment_date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
