# Generated by Django 5.2.5 on 2025-08-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0007_alter_space_number"),
        ("users", "0007_member_employment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to="spaces.space",
                unique=True,
            ),
        ),
    ]
