# Generated by Django 5.2.5 on 2025-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_member_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="employment_date",
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
